# Use the official Ubuntu base image
FROM ubuntu:24.04

# Set the maintainer label
LABEL maintainer="denis.itpro@gmail.com"

# Update the package list and install the necessary utilities
RUN apt-get update && \
    apt-get install -y \
    net-tools \
    nano \
    iputils-ping \ 
    tar \
    curl \
    wget \
    netcat-traditional \
    tcpdump \
    traceroute \
    telnet \
    nmap \
    jq \
    dnsutils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set a default command for the container
CMD ["bash"]