name: publish net-tools

on:
  push:
    paths:
      - 'net-tools/*'  # only debug
#      - net-tools/version.txt


jobs:
  download:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image_folder: ['net-tools']

    env:  # set global vas
      DOCKER_REPO: denisitpro/net-tools
      DOCKER_FILE: Dockerfile
      UBUNTU_IMAGE_VERSION: "24.04"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version
        id: vars
        run: |
          cd ${{ matrix.image_folder }}
          echo "VERSION=$(cat version.txt)"
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.image_folder }}
          file: ./${{ matrix.image_folder }}/:${{ env.DOCKER_FILE }}
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ env.VERSION }}
            ${{ env.DOCKER_REPO }}:latest
          build-args: |
            TIMESTAMP=${{ env.TIMESTAMP }}
            VERSION=${{ env.VERSION }}
            UBUNTU_IMAGE_VERSION=${{ env.UBUNTU_IMAGE_VERSION }}